filegroup(
    name = "maven-project",
    srcs = glob(
        [
            "lib/**",
            "pom.xml",
            "src/**",
            "target/**",
        ],
    ),
    visibility = ["//visibility:public"],
)
